### ISSUE TITLE
IndexError: index 40 is out of bounds for axis 0 with size 14

### ISSUE THREAD

**Issue by techaitr** [svpino/tf_object_detection_cm#10]
Hi,I have checked the closed issues but I still have the following error what could be a reason?

```
Traceback (most recent call last):
  File "confusion_matrix.py", line 142, in <module>
    tf.app.run(main)
  File "C:\Users\Sinan\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "confusion_matrix.py", line 137, in main
    confusion_matrix = process_detections(FLAGS.detections_record, categories)
  File "confusion_matrix.py", line 96, in process_detections
    confusion_matrix[groundtruth_classes[i] - 1][detection_classes[int(matches[matches[:,0] == i, 1][0])] - 1] += 1
IndexError: index 40 is out of bounds for axis 0 with size 14
```
My previous processes;

I ran this command >
python infer_detections.py --input_tfrecord_paths=C:/tensorflow1/models/research/object_detection/test.record --C:/tensorflow1/models/research/object_detection/train.record --output_tfrecord_path=C:/tensorflow1/models/research/object_detection/inference_graph/detections.tfrecord --inference_graph=C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb
 
and  The detections.tfrecord file occurred in the inference_graph folder.

**Comment by svpino** [comment]
The problems seem to be with the number of classes that you are trying to handle. You are getting an index out of bounds, so take a look around that.

**Comment by techaitr** [comment]
I want to give information about my project. my classes are "Q, R, 0, 1, 2, 3, 4, 5, 6, 7, 8 ,9 ,Y" so there are 13 classes.

I reviewed the code. if I change this part this way. 
```
IOU THRESHOLD = 0.8
CONFIDENCE THRESHOLD = 0.5
```
I get this result.

Confusion Matrix:
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  71.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  30.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  81.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  59.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  31.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  67.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  62.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  34.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  47.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  20.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 102.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  43.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

confusion_matrix.py:112: RuntimeWarning: invalid value encountered in double_scalars
 precision = float(confusion_matrix[id, id] / total_predicted)
precision_Q@0.8IOU: nan
recall_Q@0.8IOU: 0.00
precision_R@0.8IOU: nan
recall_R@0.8IOU: 0.00
precision_0@0.8IOU: nan
recall_0@0.8IOU: 0.00
precision_1@0.8IOU: nan
recall_1@0.8IOU: 0.00
precision_2@0.8IOU: nan
recall_2@0.8IOU: 0.00
precision_3@0.8IOU: nan
recall_3@0.8IOU: 0.00
precision_4@0.8IOU: nan
recall_4@0.8IOU: 0.00
precision_5@0.8IOU: nan
recall_5@0.8IOU: 0.00
precision_6@0.8IOU: nan
recall_6@0.8IOU: 0.00
precision_7@0.8IOU: nan
recall_7@0.8IOU: 0.00
precision_8@0.8IOU: nan
recall_8@0.8IOU: 0.00
precision_9@0.8IOU: nan
recall_9@0.8IOU: 0.00
precision_Y@0.8IOU: nan
recall_Y@0.8IOU: 0.00

Do you have any idea?


When I created "Detections.tfrecord", I used the training and test data I used to cultivate. I think I made a mistake. I have to do it using new data and training data. is this true ?

Thank you,

**Comment by techaitr** [comment]
I found my the problem. I tried with new validation dataset and it's done.
