### ISSUE TITLE
How to deal with expected str instance, bytes found ERROR?

### ISSUE THREAD

**Issue by jafar-pivotchain** [svpino/tf_object_detection_cm#19]
got the following error while runnin the confusion matrix file.  
`File "/home/jafar/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/metrics/tf_example_parser.py", line 49, in parse     self.field_name].HasField("bytes_list") else None TypeError: sequence item 0: expected str instance, bytes found Terminated`

**Comment by svpino** [comment]
See issue #1 .
