### ISSUE TITLE
the result output is zero, what is the problem

### ISSUE THREAD

**Issue by JerrySor** [svpino/tf_object_detection_cm#24]
I followed as you instruction but I still have the problem with result:

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
Processed 100 images
Processed 200 images
Processed 300 images
Processed 400 images
Processed 400 images

Confusion Matrix:
(array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 83.,  56.,  53.,  48.,  92., 103.,  94.,  80.,  15.,  38., 150.]]), '\n')
confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
  recall = float(confusion_matrix[id, id] / total_target)
  category  precision_@0.6IOU  recall_@0.6IOU
0        1                0.0             NaN
1        2                0.0             NaN
2        3                0.0             NaN
3        4                0.0             NaN
4        5                0.0             NaN
5        6                0.0             NaN
6        7                0.0             NaN
7        8                0.0             NaN
8        9                0.0             NaN
9        0                0.0             NaN

**Comment by JerrySor** [comment]
I followed as you instruction but I still have the problem with result:

Instructions for updating:
Use eager execution and:
tf.data.TFRecordDataset(path)
Processed 100 images
Processed 200 images
Processed 300 images
Processed 400 images
Processed 400 images

Confusion Matrix:
(array([[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 83., 56., 53., 48., 92., 103., 94., 80., 15., 38., 150.]]), '\n')
confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
recall = float(confusion_matrix[id, id] / total_target)
category precision_@0.6IOU recall_@0.6IOU
0 1 0.0 NaN
1 2 0.0 NaN
2 3 0.0 NaN
3 4 0.0 NaN
4 5 0.0 NaN
5 6 0.0 NaN
6 7 0.0 NaN
7 8 0.0 NaN
8 9 0.0 NaN
9 0 0.0 NaN

**Comment by JerrySor** [comment]
I followed as you instruction but I still have the problem with result:

Instructions for updating:
Use eager execution and:
tf.data.TFRecordDataset(path)
Processed 100 images
Processed 200 images
Processed 300 images
Processed 400 images
Processed 400 images

Confusion Matrix:
(array([[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 83., 56., 53., 48., 92., 103., 94., 80., 15., 38., 150.]]), '\n')
confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
recall = float(confusion_matrix[id, id] / total_target)
category precision_@0.6IOU recall_@0.6IOU
0 1 0.0 NaN
1 2 0.0 NaN
2 3 0.0 NaN
3 4 0.0 NaN
4 5 0.0 NaN
5 6 0.0 NaN
6 7 0.0 NaN
7 8 0.0 NaN
8 9 0.0 NaN
9 0 0.0 NaN

**Comment by JerrySor** [comment]
I followed as you instruction but I still have the problem with result:

Instructions for updating:
Use eager execution and:
tf.data.TFRecordDataset(path)
Processed 100 images
Processed 200 images
Processed 300 images
Processed 400 images
Processed 400 images

Confusion Matrix:
(array([[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 83., 56., 53., 48., 92., 103., 94., 80., 15., 38., 150.]]), '\n')
confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
recall = float(confusion_matrix[id, id] / total_target)
category precision_@0.6IOU recall_@0.6IOU
0 1 0.0 NaN
1 2 0.0 NaN
2 3 0.0 NaN
3 4 0.0 NaN
4 5 0.0 NaN
5 6 0.0 NaN
6 7 0.0 NaN
7 8 0.0 NaN
8 9 0.0 NaN
9 0 0.0 NaN

**Comment by JerrySor** [comment]
I followed as you instruction but I still have the problem with result:

Instructions for updating:
Use eager execution and:
tf.data.TFRecordDataset(path)
Processed 100 images
Processed 200 images
Processed 300 images
Processed 400 images
Processed 400 images

Confusion Matrix:
(array([[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[ 83., 56., 53., 48., 92., 103., 94., 80., 15., 38., 150.]]), '\n')
confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
recall = float(confusion_matrix[id, id] / total_target)
category precision_@0.6IOU recall_@0.6IOU
0 1 0.0 NaN
1 2 0.0 NaN
2 3 0.0 NaN
3 4 0.0 NaN
4 5 0.0 NaN
5 6 0.0 NaN
6 7 0.0 NaN
7 8 0.0 NaN
8 9 0.0 NaN
9 0 0.0 NaN

**Comment by harshit-777** [comment]
> I followed as you instruction but I still have the problem with result:
> 
> Instructions for updating:
> Use eager execution and:
> `tf.data.TFRecordDataset(path)`
> Processed 100 images
> Processed 200 images
> Processed 300 images
> Processed 400 images
> Processed 400 images
> 
> Confusion Matrix:
> (array([[ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
> [ 83., 56., 53., 48., 92., 103., 94., 80., 15., 38., 150.]]), '\n')
> confusion_matrix.py:116: RuntimeWarning: invalid value encountered in double_scalars
> recall = float(confusion_matrix[id, id] / total_target)
> category [precision_@0.6IOU](mailto:precision_@0.6IOU) [recall_@0.6IOU](mailto:recall_@0.6IOU)
> 0 1 0.0 NaN
> 1 2 0.0 NaN
> 2 3 0.0 NaN
> 3 4 0.0 NaN
> 4 5 0.0 NaN
> 5 6 0.0 NaN
> 6 7 0.0 NaN
> 7 8 0.0 NaN
> 8 9 0.0 NaN
> 9 0 0.0 NaN

Hello Do you have solution of it facing same issue
