### ISSUE TITLE
unable to generate TFRecord File using infer_detection.py

### ISSUE THREAD

**Issue by Hasnain1997-ai** [svpino/tf_object_detection_cm#37]
Infer_detection.py file requires Frozen_graph.pb file but it is not generated in TF2.
So I am using saved_model.pb file for  infer_detection.py as:
python3 infer_detections.py --input_tfrecord_paths=-----/test.record --output_tfrecord_path=---/output_record/test.tfrecord  --inference_graph=---saved_model/saved_model.pb
--- represend my directrory.
The error I get is:

inference/detection_inference.py", line 71, in build_inference_graph
    graph_def.MergeFromString(graph_content)
google.protobuf.message.DecodeError: Error parsing messageence/detection_inference.py", line 71, in build_inference_graph
    graph_def.MergeFromString(graph_content)
google.protobuf.message.DecodeError: Error parsing message

Please help in generating this Tf record filw

**Comment by Critique831** [comment]
Hi, may I know how you solved this? Thanks
