### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 442: invalid start byte

### ISSUE THREAD

**Issue by shahmustafa** [svpino/tf_object_detection_cm#5]
I am getting an error while generating a detection record
I tried by changing the mode here `with tf.gfile.Open(inference_graph_path, 'rb') as graph_def_file:` in detection_inference.py line No.68. But I am getting the same error, could you help me out

**Comment by svpino** [comment]
Take a look at issue #1 and see if that helps. If it doesn't, do you mind sharing the full stack trace?
